#!/bin/bash
#add arcadeall,mame in console.csv
#playstation_1,psx
#super_nintendo,snes
#check rest of consoles , use diff
#sed -e 's/sed -e 's/^/"/' error.log > badvids.log
# sed -e 's/sed -e 's/^/rm /' error.log > badvids.log
echo "Daphne Renames"
cd /home/pi/pixelcade/lcdmarquees
cp daphne-dlair.jpg "daphne-Dragons Lair.jpg"
cp daphne-cliff.jpg "daphne-Cliff Hanger.jpg"
cp daphne-ace.jpg "daphne-Space Ace.jpg"
cp daphne-cobraab.jpg "daphne-Cobra Command.jpg"
cp daphne-mach3.jpg "daphne-MACH 3.jpg"
echo "MP4 Delete Bad Vids"
cd /home/pi/pixelcade/mp4marquees
rm "Metroid Prime.mp4"
rm "urassic Park I.mp4"
rm "Super Castlevania IV.mp4"
rm "_chqflag.mp4"
rm "R-Type III.mp4"
rm "Super Double Dragon.mp4"
rm "Tony Hawk 3.mp4"
rm "Zombies Ate My Neighbors.mp4"
rm "Jungle Strike.mp4"
rm "Super Ghouls n Ghosts.mp4"
rm "Super Smash Bros Melee.mp4"
rm "_bakutotu.mp4"
rm "Super Valis IV.mp4"
rm "nduror.mp4"
rm "Confidential Mission.mp4"
rm "Street Fighter Alpha 3 Max.mp4"
rm "Rock n Roll Racing.mp4"
rm "Harvest Moon.mp4"
rm "Ninja Gaiden Trilogy.mp4"
rm "Ridge Racer.mp4"
rm "Space Megaforce (USA).mp4"
rm "_captcomm.mp4"
rm "James Pond.mp4"
rm "Super Tennis.mp4"
rm "Super Mario Kart.mp4"
rm "across2.mp4"
rm "of2.mp4"
rm "Super R Type.mp4"
rm "_aso.mp4"
rm "Super Punch-Out!!.mp4"
rm "Dragon's Revenge.mp4"
rm "Super Turrican II.mp4"
rm "High Seas Havoc.mp4"
rm "_cybots.mp4"
rm "_nspirit.mp4"
rm "Donkey Kong 64 (USA).mp4"
rm "Super Mario World 1.mp4"
rm "_dynduke.mp4"
rm "Super Putty.mp4"
rm "PaRappa the Rapper.mp4"
rm "_aliensyn.mp4"
rm "F Zero.mp4"
rm "James Pond 3.mp4"
rm "Legend of the Mystical Ninja.mp4"
rm "oul Calibur.mp4"
rm "_blazstar.mp4"
rm "N. Squadron -USA-.mp4"
rm "Illusion of Gaia.mp4"
rm "Legendary Axe II.mp4"
rm "inhaender (USA).mp4"
rm "Super Star Wars III.mp4"
rm "_gradius.mp4"
rm "Mega Man Soccer.mp4"
rm "_b2b.mp4"
rm "Super Star Wars.mp4"
rm "T.N.K. III.mp4"
rm "Mega Man X2.mp4"
rm "Lion King, The.mp4"
rm "Advanced Busterhawk Gleylancer.mp4"
rm "_doubledr.mp4"
rm "_mvscb.mp4"
rm "Stunt Race FX.mp4"
rm "Operation Logic Bomb.mp4"
rm "_citycon.mp4"
rm "_mvp.mp4"
rm "God of War II.mp4"
rm "Phalanx - The Enforce Fighter A-144 (USA).mp4"
rm "_baddudes.mp4"
rm "Firepower 2000 (USA).mp4"
rm "Ninja Warriors.mp4"
rm "_chasehq.mp4"
rm "Sonic The Hedgehog II.mp4"
rm "baction.mp4"
rm "Comix Zone.mp4"
rm "Sonic Knuckles II.mp4"
rm "_altbeast.mp4"
rm "onic Adventure 2.mp4"
rm "winfalc.mp4"
rm "rlegend2play.mp4"
rm "r. Do Fixed.mp4"
rm "Mega Man 7.mp4"
rm "_bchopper.mp4"
rm "Star Wars Rogue Squadron II.mp4"
rm "47 Aces.mp4"
rm "Sonic Adventure 1.mp4"
rm "Tekken 2 (USA) (v1.1).mp4"
rm "Secret of Evermore.mp4"
rm "Rolling Thunder 3.mp4"
rm "ackie Chan's Action Kung Fu.mp4"
rm "Death and Return of Superman.mp4"
rm "U.N. Squadron snes.mp4"
rm "SHOCK TROOPERS.mp4"
rm "_aburner.mp4"
rm "tar Fox 64.mp4"
rm "park.mp4"
rm "Super Mario All Stars.mp4"
rm "si.mp4"
rm "Toejam and Earl.mp4"
rm "allybik.mp4"
rm "1080 Avalanche.mp4"
rm "pace Invaders II (Midway, cocktail).mp4"
rm "ECCO the Dolphin.mp4"
rm "_bjourney.mp4"
rm "Cannon Spike.mp4"
rm "Splatterhouse 2.mp4"
rm "_centiped.mp4"
rm "treets of Rage III.mp4"
rm "Twinkle Star Sprites.mp4"
rm "Sonic The Hedgehog I.mp4"
rm "El Viento.mp4"
rm "GoldenEye (USA).mp4"
rm "Twinkle Tale.mp4"
rm "amuraia.mp4"
rm "Legend of Zelda, The - A Link to the Past & Four Swords.mp4"
rm "Battletoads in Battlemaniacs.mp4"
rm "Super Turrican I.mp4"
rm "Tetris Attack.mp4"
rm "drift.mp4"
rm "epulse.mp4"
rm "Secret of Mana.mp4"
rm "Super Bomberman V.mp4"
rm "_lastbld2.mp4"
rm "Metroid Prime 2.mp4"
rm "Gradius V.mp4"
rm "_3wonders.mp4"
rm "Lost Vikings I.mp4"
rm "_abcop.mp4"
rm "Castlevania Harmony of Dissonance.mp4"
rm "iscs of Tron.mp4"
rm "_astyanax.mp4"
rm "Battletoads and Double Dragon.mp4"
rm "ocky Rocky I.mp4"
rm "WipEout Pulse.mp4"
rm "Street Fighter II Turbo SNES.mp4"
rm "Spindizzy Worlds.mp4"
rm "Out of This World.mp4"
rm "Mega Man X3.mp4"
rm "Pikmin 2.mp4"
rm "Castlevania - Symphony of the Night.mp4"
rm "Final Fight II.mp4"
rm "jammers.mp4"
rm "Legend of Zelda The Ocarina of Time.mp4"
rm "Mega Man X5 (USA).mp4"
rm "Cannon Fodder.mp4"
rm "Pokemon - Ruby Version.mp4"
rm "Super Star Wars II.mp4"
rm "trider.mp4"
rm "Demons Crest.mp4"
rm "Biker Mice from Mars.mp4"
rm "_aof.mp4"
rm "hedeep.mp4"
rm "_dayto2pe.mp4"
rm "Alien III.mp4"
rm "Project Justice.mp4"
rm "_mslugx.mp4"
rm "_mvsc.mp4"
rm "Kirby's Dream Course (USA).mp4"
rm "Metroid Fusion.mp4"
rm "Jim Power - The Lost Dimension in 3D.mp4"
rm "Indiana Jones and the Last Crusade.mp4"
rm "Storm Blade.mp4"
rm "Super Metroid.mp4"
rm "Second Samurai.mp4"
rm "Star Fox.mp4"
rm "Batman Returns.mp4"
rm "ime Pilot '84 (Set 2).mp4"
rm "oe & Mac 2 - Lost in the Tropics.mp4"
rm "_lastduel.mp4"
rm "Kirby's Dream Land 3.mp4"
rm "eenage Mutant Ninja Turtles The Hyperstone Heist.mp4"
rm "USHA.mp4"
rm "Alien vs Predator.mp4"
rm "drun2.mp4"
rm "almndr2.mp4"
rm "achero.mp4"
rm "_nrallyx.mp4"
rm "hadow of the Beast I.mp4"
rm "_captaven.mp4"
rm "Man Overboard.mp4"
rm "Final Fight III.mp4"
rm "Imperium (USA).mp4"
rm "Mega Turrican.mp4"
rm "Super James Pond.mp4"
rm "Ghoul Patrol.mp4"
rm "_columns2.mp4"
rm "_gowcaizr.mp4"
rm "Bio Hazard Battle.mp4"
rm "Chrono Trigger.mp4"
rm "_blktiger.mp4"
rm "Donkey Kong Country II.mp4"
rm "_goalx3.mp4"
rm "Road Rash III.mp4"
rm "_ddragon3.mp4"
rm "Border Down.mp4"
rm "Tekken 5.mp4"
rm "_cninja.mp4"
rm "Advance Wars.mp4"
rm "Pokemon - Emerald Version.mp4"
rm "Kirby Super Star.mp4"
rm "Burnout 3.mp4"
rm "_badlands.mp4"
rm "R4 - Ridge Racer Type 4 (USA).mp4"
rm "Thunder Force IV.mp4"
rm "_asteroid.mp4"
rm "_mspacman.mp4"
rm "_nbajam.mp4"
rm "Wave Race 64.mp4"
rm "unforce.mp4"
rm "F-Zero GX.mp4"
rm "Ecco Jr.mp4"
rm "_bgaregga.mp4"
rm "Spyro the Dragon (USA).mp4"
rm "Micro Machines 2.mp4"
rm "Game & Watch Gallery 4.mp4"
rm "Ninjas Kick Back.mp4"
rm "_mslug5.mp4"
rm "_jrpacman.mp4"
rm "Legend of Zelda Link to the Past.mp4"
rm "_aliencha.mp4"
rm "080 Snowboarding (Europe) (En,Ja,Fr,De).mp4"
rm "James Pond 2.mp4"
rm "Pinball Dream .mp4"
rm "First Samurai.mp4"
rm "Crash Bandicoot - Warped (USA).mp4"
rm "Prince of Persia.mp4"
rm "_landmakr.mp4"
rm "oof Troop.mp4"
rm "rusty's Super Fun House.mp4"
rm "egulus.mp4"
rm "Sonic Pinball Party.mp4"
rm "Tekken (USA).mp4"
rm "ioship.mp4"
rm "Wild Guns.mp4"
rm "_gradius4.mp4"
rm "rkanoid (unl.lives, slower).mp4"
rm "Choplifter III.mp4"
rm "Metal Warriors.mp4"
rm "Wave Race Blue Storm.mp4"
rm "Lords of Thunder.mp4"
rm "iveside.mp4"
rm "Mega Man Zero (USA).mp4"
rm "Whip Rush.mp4"
rm "_androdun.mp4"
rm "Beyond Oasis.mp4"
rm "Castlevania Dracula X.mp4"
rm "_crusnusa.mp4"
rm "Drill Dozer (USA).mp4"
rm "_bionicc.mp4"
rm "Conker's Bad Fur Day (USA).mp4"
rm "Aero the Acro-Bat.mp4"
rm "Kirby Air Ride.mp4"
rm "Magical Quest.mp4"
rm "Banjo-Kazooie (USA).mp4"
rm "Donkey Kong Country III.mp4"
rm "Great Circus Mystery.mp4"
rm "Lost Vikings II.mp4"
rm "Super Mario World II.mp4"
rm "_batman.mp4"
rm "Rendering Ranger R2.mp4"
rm "Adventures of Batman & Robin.mp4"
rm "Tiny Toon Adventures.mp4"
rm "Kirby's Avalanche (USA).mp4"
rm "Kirby & the Amazing Mirror.mp4"
rm "_dbz2.mp4"
rm "Desert Strike.mp4"
rm "Tetris and Dr. Mario.mp4"
rm "Soldiers of Fortune.mp4"
rm "Loco Roco 2.mp4"
rm "Spider-Man & Venom - Maximum Carnage.mp4"
rm "Super Bonk.mp4"
rm "Wario's Woods.mp4"
rm "urbofrc.mp4"
rm "Daytona USA.mp4"
rm "ate of Thunder.mp4"
rm "ow.mp4"
rm "F-Zero - GP Legend (USA).mp4"
rm "Teenage Mutant Ninja Turtles IV.mp4"
rm "General Chaos.mp4"
rm "Zero Gunner 2.mp4"
rm "_bwidow.mp4"
rm "Dynamite Headdy.mp4"
rm "_blazlaz.mp4"
rm "Donkey Kong Country I.mp4"
rm "Star Fox Adventures.mp4"
rm "_cotton2.mp4"
rm "Kirby - Nightmare in Dream Land.mp4"
rm "Super Mario RPG.mp4"
rm "Metal Gear Solid 3.mp4"
rm "_battlera.mp4"
rm "ocky Rocky II.mp4"
rm "Maui Mallard in Cold Shadow.mp4"
rm "Street Fighter Alpha 3 Upper.mp4"
rm "Einhaender (USA).mp4"
